Jacobi method for `symmetric eigen value proble`, below is the computational implementaton of the Jacobi algorithm for solving for the eigen values of the `symmetric` matrix, I shall make use of the python packages like `numpy` and some others if I find it useful, hey I don't know yet dont judge me, let's see.

`Importing libraries`


In [1]:
import numpy as np 

This is the function that is responsible for `rotations` if you know the `Jacobi` algorithm then you know it should have rotation matrix say `R` in every say `i-th` iteration, 

this `jacobi_rotation` function will then calculates the `rotation matrix  R` for the largest off-diagonal element

In [4]:
def jacobi_rotation(A, i, j):
    if A[i, i] == A[j, j]:
        theta = np.pi / 4
    else:
        theta = 0.5 * np.arctan(2 * A[i, j] / (A[i, i] - A[j, j]))
    
    c = np.cos(theta)
    s = np.sin(theta)
    #this is just building the rotation matrix as we know it right, this is useful when doing the similar transformations
    R = np.identity(len(A))
    R[i, i] = c
    R[j, j] = c
    R[i, j] = s
    R[j, i] = -1*s
    
    return R

Now we're ready to define the `Jacobi method` algorithm, this will be responsible to then perform the iterations, see the function below.

this function takes in the matrix, and there's also the `maximum iterations`, and the `tolerance` which is free to be changed and set to anything

In [5]:
def jacobi_method(A, tol=1e-200000, max_iterations=430):
    n = len(A)
    eigenvectors = np.identity(n)
    
    for it in range(max_iterations):
        # Find the largest off-diagonal element
        off_diagonal = np.tril(A, -1)
        i, j = np.unravel_index(np.argmax(np.abs(off_diagonal)), A.shape)
        
        # Stop if the off-diagonal elements are below the tolerance
        #stop when the off-diagonal elements are zero.
        if np.abs(A[i, j]) ==0:
            break
        
        # Compute the rotation matrix
        R = jacobi_rotation(A, i, j)
        
        # Update the matrix A
        #A = R.T @ A @ R #@ is just for matrix maltiplications, I was recently released, so basically to multiply the matrices say A and B, in numpy you do np.dot(A,B) the short hand for this which is more efficient, this is just shorthand and should not be intimidating
        print(f"{it} : \n {A}")

        B=np.dot(R.T,A)
        A=np.dot(B,R)
        # Update the eigenvectors
        eigenvectors = eigenvectors @ R
    
    eigenvalues = np.diag(A)
    return eigenvalues, eigenvectors


That's it, we can now go ahead and test our function, below is the code that reads in a

`symmetric n×n` and then goes ahead and calculate the eigenvalues and then eigenvects of the matrix.

In [6]:
# A = np.array([
#                 [2,0,0],
#                 [0,3,0],
#                 [0,0,8]
#               ])
# # 1 3 4
# # 3 2 8
# # 4 8 3
# eigenvalues = jacobi_method(A)

# print("Eigenvalues:", eigenvalues)
# # print("Eigenvectors:\n", eigenvectors)



import numpy as np

# A = np.array([
#     [4, 1, 2],
#     [1, 2, 3],
#     [2, 3, 6]
# ])
A=np.array([
    [1,3,4],
    [3,2,8],
    [4,8,3]
])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = jacobi_method(A)

print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)



0 : 
 [[1 3 4]
 [3 2 8]
 [4 8 3]]
1 : 
 [[ 1.          4.92527227  0.86121604]
 [ 4.92527227 10.45323148  0.99805258]
 [ 0.86121604  0.99805258 -5.45323148]]
2 : 
 [[ 6.00749901  6.82057973  1.18363228]
 [ 6.82057973  5.44573247  0.58035905]
 [ 1.18363228  0.58035905 -5.45323148]]
3 : 
 [[-1.07663025  0.56129078  0.45215556]
 [ 0.56129078 12.52986173  1.23828808]
 [ 0.45215556  1.23828808 -5.45323148]]
4 : 
 [[-1.07663025  0.52906123  0.48947544]
 [ 0.52906123 12.27685044  2.45341972]
 [ 0.48947544  2.45341972 -5.20022019]]
5 : 
 [[-1.07663025  0.45733565  0.55707817]
 [ 0.45733565 11.2883738   4.72417805]
 [ 0.55707817  4.72417805 -4.21174356]]
6 : 
 [[-1.07663025  0.28972869  0.65996157]
 [ 0.28972869  7.69695714  8.06764924]
 [ 0.65996157  8.06764924 -0.6203269 ]]
7 : 
 [[-1.07663025 -0.09611304  0.71432085]
 [-0.09611304 -1.72727409  7.39289104]
 [ 0.71432085  7.39289104  8.80390434]]
8 : 
 [[-1.07663025  0.24185749  0.67896756]
 [ 0.24185749  6.50517098  8.57782222]
 [ 0.67896756 